name: Build Package
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: python -m pip install -U build setuptools
      - name: Build
        run: python -m build
      - name: package file
        run: ls dist
