name: Test Package
on:
  push:
    branches:
    - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Running test.py
        run: python test.py
